"""003_add_user_id_to_usage_log

Revision ID: a18551e9610e
Revises: dc86348d8aef
Create Date: 2026-05-08 03:21:24.297752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18551e9610e'
down_revision: Union[str, None] = 'dc86348d8aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'usage_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_column('usage_logs', 'user_id')
    # ### end Alembic commands ###
